version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_folder: C:\TheCrafters001\Build\Forest-OE\src\bin
before_build:
- ps: nuget restore 'C:\TheCrafters001\Build\Forest-OS\src\bin\src\Forest OE.sln'
build:
  project: src\Forest OE.sln
  verbosity: minimal